baseURL = 'http://ravitejak.com'
languageCode = 'en-us'
title = 'Ravi Teja K | A developers journey.'
theme='Toha'
[data]
author='Ravi Teja K'
# Background image of the landing page
[params]
backgroundImage= '/images/background.jpg'
# specify whether you want to write some blog posts or not
enableBlogPost= true
# specify whether you want to show Table of Contents in reading page
enableTOC= true

# Provide newsletter configuration. This feature hasn't been implemented yet.
# Currently, you can just hide it from the footer.
[params.newsletter]
enable= false

[params.logo]
# Provide logos for your site. The inverted logo will be used in the initial
# transparent navbar and the main logo will be used in the non-transparent navbar.
main='/images/main-logo.png'
inverted='/images/inverted-logo.png'
favicon='/images/favicon.png'
[params.features.porfolio]
# Configure various features of this theme
# Enable and configure portfolio
enable= true
[params.features.blog]
# Enable and configure blog posts
enable= true
# Share post on different social media
[params.features.blog.shareButtons]
facebook= true
twitter= true
linkedin= true
reddit= true
whatsapp= true
email= true
# tumblr= true
# pocket= true
# diaspora= true
# mastodon= true
[params.features.notes]
# Enable & configure "Notes" features
enable= true
# Enable comment feature. There, should be only one of them.
[params.features.comment]
enable= false
[params.features.comment.disqus]
shortName='toha-example-site'
# valine:
#   appId: HTV6askWxVo3vOxlqjjaq2hd-MsYXbMMI
#   appKey: pVrT3C85KGIuk27t07eh6bUC
#   avatar: retro
#   placeholder: Share your thought.
#   lang: en
#   recordIP: true
#   enableQQ: true
# specify whether you want to show Table of Contents in reading page
enableTOC= true
# Show tags under the post title
enableTags= true
# If you want to use different country flag for a language, specify them here.
[params.features.flagOverwrites]
languageCode='en'
countryCode= 'in'
# Provide footer configuration.
[params.footer]
enable= true
# You can provide your custom footer template using this option.
# Put your template in "layouts/partials" folder of your repo.
template='footer.html'
# Show/hide navigation in the footer. Default is "true".
[params.footer.navigation]
enable= false
# Show/hide "Contact Me" section in the footer. Default is "true".
[params.footer.navigation.contactMe]
enable= false
# Show/hide credentials section in the footer. Default is "true".
[params.footer.navigation.credentials]
enable= false
# Show/hide newsletter section in the footer. Default is "true".
# Currently, it supports "mailchimp".
[params.footer.newsletter]
enable= false
provider='mailchimp'
mailchimpURL= 'https://github.us1.list-manage.com/subscribe/post?u=19de52a4603135aae97163fd8&amp;id=094a24c76e'
# Show/hide disclaimer notice in the footer. Default is "false".
[params.footer.disclaimer]
enable= true